#!/bin/bash
#############################################

#First process the Measured data
#calculate the mean zs (i.e. used to compare performance on wave setup)
#First process the Measured data
#calculate the mean zs (i.e. used to compare performance on wave setup)
#First process the Measured data
#calculate the mean zs (i.e. used to compare performance on wave setup)
ZSCMES=`gmtmath CrestWL_Measured.txt -C1 MEAN = | awk 'END{printf("%2.2f",$2-10.13)}'`
# WARNING Removed another 0.3 WL here as expected mean WL is 1.26
ZSSMES=`gmtmath ShoreWL_Measured.txt -C1 MEAN = | awk 'END{printf("%2.2f",$2-10.13-0.3)}'`


LPfilt=16

filter=c

overlap=1024
df=`echo 1/${overlap} | bc -l`

# Processing Hig
filter1d CrestWL_Measured.txt -F${filter}${LPfilt} -E > filtered.txt
spectrum1d filtered.txt -S${overlap} -i1 -Ndata > measSpec_Long_Crest.txt
HIGCMES=`gmtmath measSpec_Long_Crest.txt -C1 SUM ${df} MUL SQRT 4 MUL = | awk 'END{printf("%2.2f",$2)}'`

filter1d ShoreWL_Measured.txt -F${filter}${LPfilt} -E > Shore_WL-filtered.txt
spectrum1d Shore_WL-filtered.txt -S${overlap} -i1 -Ndata > measSpec_Long_Shore.txt
HIGSMES=`gmtmath measSpec_Long_Shore.txt -C1 SUM ${df} MUL SQRT 4 MUL = | awk 'END{printf("%2.2f",$2)}'`

#processing Hs for short waves
filter1d CrestWL_Measured.txt -F${filter}${LPfilt}+h -E > filtered.txt
spectrum1d filtered.txt -S${overlap} -i1 -Ndata > measSpec_Short_Crest.txt
HSCMES=`gmtmath measSpec_Short_Crest.txt -C1 SUM ${df} MUL SQRT 4 MUL = | awk 'END{printf("%2.2f",$2)}'`

filter1d ShoreWL_Measured.txt -F${filter}${LPfilt}+h -E > Shore_WL-filtered-HP.txt
filter1d Shore_WL-filtered-HP.txt -Fg4 -E > Shore_WL-filtered-HP3LP.txt
spectrum1d Shore_WL-filtered-HP3LP.txt -S${overlap} -i1 -Ndata > measSpec_Short_Shore.txt
HSSMES=`gmtmath measSpec_Short_Shore.txt -C1 SUM ${df} MUL SQRT 4 MUL  = | awk 'END{printf("%2.2f",$2)}'`

echo "Measured data"
echo "Hs-Crest= ${HSCMES}; Hig-Crest= ${HIGCMES}; zs-mean-Crest= ${ZSCMES};"
echo "Hs-Shore= ${HSSMES}; Hig-Shore= ${HIGSMES}; zs-mean-Shore= ${ZSSMES};"



echo "DiffZsShore DiffHigShore DiffHsShore" > XB-RBFoutput.txt


#`seq 100`
for i in `seq 20`
do
  numi=`printf "%03d" ${i} `



  gmtselect RBF-test_${numi}_Crest.txt -R1023/3072/-5/5 >rawdata.txt
  ZSCrest=`gmtmath rawdata.txt -C1 MEAN = | awk 'END{printf("%2.2f",$2)}'`
  HSCrest=`gmtmath rawdata.txt -C2 MEAN = | awk 'END{printf("%2.2f",$3*1.4142)}'`
  gmtmath rawdata.txt -C0 -1023 ADD = rawd.txt
  gmtmath -T1/2048/1 -N1/0 = samptime.txt
  sample1d rawd.txt -Nsamptime.txt >sampRaw.txt
  filter1d sampRaw.txt -F${filter}${LPfilt} -E > filtered.txt
  spectrum1d filtered.txt -S${overlap} -i1 -Ndata > Spec_Long_Crest.txt

  #spectrum1d CrestWL_Measured.txt -S${overlap} -i1 -Ndata > measSpec_All_Crest.txt
  #HSCMES=`gmtselect measSpec_All_Crest.txt -R0.04/0.333/-5/5000000 | gmtmath STDIN -C1 SUM ${df} MUL SQRT 4 MUL  = | awk 'END{printf("%2.2f",$2)}'`
  #HIGCMES=`gmtselect measSpec_All_Crest.txt -R0/0.04/-5/5000000 | gmtmath STDIN -C1 SUM ${df} MUL SQRT 4 MUL  = | awk 'END{printf("%2.2f",$2)}'`

  #spectrum1d ShoreWL_Measured.txt -S${overlap} -i1 -Ndata > measSpec_All_Shore.txt
  #HSSMES=`gmtselect measSpec_All_Shore.txt -R0.04/0.333/-5/5000000 | gmtmath STDIN -C1 SUM ${df} MUL SQRT 4 MUL  = | awk 'END{printf("%2.2f",$2)}'`
  #HIGSMES=`gmtselect measSpec_All_Shore.txt -R0/0.04/-5/5000000 | gmtmath STDIN -C1 SUM ${df} MUL SQRT 4 MUL  = | awk 'END{printf("%2.2f",$2)}'`
  HIGCrest=`gmtmath Spec_Long_Crest.txt -C1 SUM ${df} MUL SQRT 4 MUL = | awk 'END{printf("%2.2f",$2)}'`


  gmtselect RBF-test_${numi}_Shore.txt -R1023/3072/-5/5 >rawdata.txt
  ZSShore=`gmtmath rawdata.txt -C1 MEAN = | awk 'END{printf("%2.2f",$2)}'`
  HSShore=`gmtmath rawdata.txt -C2 MEAN = | awk 'END{printf("%2.2f",$3*1.4142)}'`
  gmtmath rawdata.txt -C0 -1023 ADD = rawd.txt
  gmtmath -T1/2048/1 -N1/0 = samptime.txt
  sample1d rawd.txt -Nsamptime.txt >sampRaw.txt
  filter1d sampRaw.txt -F${filter}${LPfilt} -E > filtered.txt
  spectrum1d filtered.txt -S${overlap} -i1 -Ndata > Spec_Long_Shore.txt
  HIGShore=`gmtmath Spec_Long_Shore.txt -C1 SUM ${df} MUL SQRT 4 MUL = | awk 'END{printf("%2.2f",$2)}'`


  DiffZsCrest=`echo "${ZSCrest}-$ZSCMES" | bc | awk 'END{printf("%2.2f",$1)}'`
  DiffHigCrest=`echo "${HIGCrest}-${HIGCMES}" | bc | awk 'END{printf("%2.2f",$1)}'`
  DiffHsCrest=`echo "${HSCrest}-${HSCMES}" | bc | awk 'END{printf("%2.2f",$1)}'`
  DiffZsShore=`echo "${ZSShore}-$ZSSMES" | bc | awk 'END{printf("%2.2f",$1)}'`
  DiffHigShore=`echo "${HIGShore}-${HIGSMES}" | bc | awk 'END{printf("%2.2f",$1)}'`
  DiffHsShore=`echo "${HSShore}-${HSSMES}" | bc | awk 'END{printf("%2.2f",$1)}'`
  printf "%2.2f\t%2.2f\t%2.2f\n" ${DiffZsShore} ${DiffHigShore} ${DiffHsShore} >> XB-RBFoutput.txt



done

# Now plot scatter clouds showing the results
#remove header from file we just created so it matches the lines in RBF-best.txt
awk '{if(NR>1){print($0)}}' XB-RBFoutput.txt > XB-RBF-nohead.txt
#glue the files together
paste RBF_best.txt XB-RBF-nohead.txt > allRBFTog.txt

region=-R-0.20/0.20/-0.20/0.20
proj=-JX8c/8c
outfile=XB_vs_RBF.ps
gmtset FONT_ANNOT_PRIMARY 10p,Helvetica FONT_TITLE 12p,Helvetica-Bold FONT_LABEL 10p,Helvetica-Bold

psbasemap $region $proj -Bxa0.05f0.01+l"XBeach_gpu error (m)" -Bya0.05f0.01+l"RBF predicted error (m)" -BWSen -K -P > $outfile
psxy  allRBFTog.txt $region $proj -Sc0.10c -Gblack -i10,7 -O -K >> $outfile
psxy  allRBFTog.txt $region $proj -St0.15c -Gblack -i11,8 -O -K >> $outfile
psxy  allRBFTog.txt $region $proj -Ss0.15c -Gblack -i12,9 -O -K >> $outfile

echo -e "-0.18 0.18\n " | psxy  $region $proj -Sc0.10c -Gblack -O -K  >> $outfile
echo "-0.18 0.18 zs error" | pstext $region $proj -F+jML+f10p,Helvetica -Dj0.2c -O -K  >> $outfile
echo -e "-0.18 0.16\n " | psxy  $region $proj -St0.10c -Gblack -O -K  >> $outfile
echo "-0.18 0.16 Hig error" | pstext $region $proj -F+jML+f10p,Helvetica -Dj0.2c -O -K  >> $outfile
echo -e "-0.18 0.14\n " | psxy  $region $proj -Ss0.10c -Gblack -O -K  >> $outfile
echo "-0.18 0.14 Hs error" | pstext $region $proj -F+jML+f10p,Helvetica -Dj0.2c -O -K  >> $outfile

psxy -R -J -T -O >> $outfile
psconvert -A -P -Tg $outfile
